<a href="https://colab.research.google.com/github/Ywodaje/Tag-INST-326/blob/main/INST326_Week1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INST326 — Week 1 Exercises (Revised): Library Management Theme  
*Generated on 2025-09-07*

This revision **removes all conditionals and all lists** to align strictly with Week 1 topics.

**Included topics**
- Variables and basic data types (`str`, `int`, `float`, `bool`)
- Basic arithmetic and expressions
- `print()` and formatted strings (f-strings, `.format`)
- `input()` for user input
- String methods: `.strip()`, `.lower()`, `.upper()`, `.replace()`, `.find()`, `.rfind()`, slicing
- Type conversion with `int()`, `float()`, `str()`
- Boolean expressions (compute and print `True/False`) **without branching**

**Excluded topics**
- Conditionals (`if`, `elif`, `else`), ternary expressions
- Lists (and methods like `.split()` which returns a list)
- Loops, dictionaries, files, functions, modules, classes

Each exercise includes a short description and a starter cell. Replace the `# Your code here` section with your work.

## Exercise 1: Book Identity Card

Create variables `title` (str), `author` (str), `year_published` (int), and `isbn` (str).  
Print: `"The Hobbit (1937) by J.R.R. Tolkien — ISBN: 9780261103344"` using an f-string.

In [11]:
title = "The Hobbit"
author = "J.R.R. Tolkien"
year_published = 1937
isbn = "9780261103344"
print(f"{title} ({year_published}) by {author} — ISBN: {isbn}")

The Hobbit (1937) by J.R.R. Tolkien — ISBN: 9780261103344


##Exercise 2: New Copies on Order


Given integers `current_copies` and `incoming_copies`, compute `total_copies` and print a message like `"Total copies after delivery: 27"`.

In [42]:
current_copies = 11
incoming_copies = 16
total_copies = current_copies + incoming_copies
print(f"Total copies after delivery: {total_copies}")

Total copies after delivery: 27


## Exercise 3: Availability Flag (No Branching)



Create `is_available` that is `True` when `current_copies > 0`. Print the boolean value.

In [43]:
current_copies = 7
is_available = current_copies > 0
print(is_available)

True


## Exercise 4: Formatting a Call Number

Given `prefix = "QA"`, `section = "76"`, `cutter = "P98"`, combine into `"QA.76.P98"` and print the result.

In [14]:
prefix = "QA"
section = "76"
cutter = "P98"
call_number = f"{prefix}.{section}.{cutter}"
print(call_number)

QA.76.P98


## Exercise 5: Trim a Title

Ask for a book title. Use `.strip()` to remove leading/trailing spaces and print the cleaned title in quotes.

In [44]:
title_input = input("Enter a book title: ")
cleaned_title = title_input.strip()
print(f'"{cleaned_title}"')

Enter a book title: Atomic Habit
"Atomic Habit"


## Exercise 6: Late Fee (Arithmetic Only)

Ask for days late (integer). Compute the fee at `$0.25` per day, **but never negative**. Use arithmetic (e.g., `max_days = (days + abs(days)) // 2`) or `max()` to ensure non‑negative days. Print `"Late fee: $X.XX"`.

In [47]:
days = int(input("Days late: "))
non_negative_days = max(days, 0)
fee = non_negative_days * 0.25
print(f"Late fee: ${fee:.2f}")

Days late: 8
Late fee: $2.00


## Exercise 7: Title Length Counter

Given a `title` string, compute the number of characters and print `"Title length: N"`.

In [50]:
title = "Computer"
length = len(title)
print(f"Title length: {length}")

Title length: 8


## Exercise 8: Case-Insensitive Match (Boolean Only)

Let `query = "dune"` and `title = "Dune"`. Compute a boolean `matches` that is `True` when they match ignoring case. Print `matches`.

In [18]:
query = "dune"
title = "Dune"
matches = query.lower() == title.lower()
print(matches)

True


## Exercise 9: Year Text to Int

Start with `year_text = "2001"`. Convert to int, add 1 to get the next reprint year, then print both values in one sentence.

In [20]:
year_text = "2001"
year_num = int(year_text)
next_reprint = year_num + 1
print(f"Original: {year_text}  Next reprint: {next_reprint}")

Original: 2001  Next reprint: 2002


## Exercise 10: Shelf Label Alignment

Given `title` and `author`, print a fixed‑width label so titles align. Example: `Title: {title:30}  Author: {author:20}`.

In [51]:
title = "The Silent Patient"
author = "Alex Michaelides"
print(f"Title: {title:30}  Author: {author:20}")

Title: The Silent Patient              Author: Alex Michaelides    


## Exercise 11: Basic Price Math

A book costs `$12.50`. A student discount of `$2.00` applies. Compute and print the final price with two decimals.

In [21]:
price = 12.50
discount = 2.00
final = price - discount
print(f"${final:.2f}")

$10.50


## Exercise 12: ISBN Normalizer

Given `isbn_raw = " 978-0-261-10334-4 "`, strip whitespace and remove dashes to get `"9780261103344"`.

In [22]:
isbn_raw = " 978-0-261-10334-4 "
isbn_clean = isbn_raw.strip().replace("-", "")
print(isbn_clean)

9780261103344


## Exercise 13: Branch Code Normalization

Given `home_branch = "  umd  "`, normalize by stripping spaces and uppercasing. Print the normalized code.

In [53]:
home_branch = " umd "
normalized = home_branch.strip().upper()
print(normalized)

UMD


## Exercise 14: Pages-per-Day (Compute Only)

Ask for `total_pages` and `days_until_due`. Compute `pages_per_day = total_pages / max(days_until_due, 1)` to avoid division by zero. Print with 1 decimal place.

In [55]:
total_pages = int(input("Total pages: "))
days_until_due = int(input("Days until due: "))
pages_per_day = total_pages / max(days_until_due, 1)
print(f"{pages_per_day:.1f}")

Total pages: 120
Days until due: 6
20.0


## Exercise 15: Call Number Parsing (No Lists)

Given `call_no = "QA.76.P98"`, extract `prefix`, `section`, and `cutter` using `.find()`/`.rfind()` and string slicing only (no `.split()`). Print them in one line.

In [25]:
call_no = "QA.76.P98"
first_dot = call_no.find(".")
last_dot = call_no.rfind(".")
prefix = call_no[:first_dot]
section = call_no[first_dot+1:last_dot]
cutter = call_no[last_dot+1:]
print(f"{prefix} {section} {cutter}")

QA 76 P98


## Exercise 16: Basic Type Introspection

Create variables `n = 10`, `price = 9.99`, `title = "Dune"`, `available = True`. Print each value and its type using `type()`.

In [56]:
n = 10
price = 9.99
title = "Dune"
available = True
print(n, type(n))
print(price, type(price))
print(title, type(title))
print(available, type(available))

10 <class 'int'>
9.99 <class 'float'>
Dune <class 'str'>
True <class 'bool'>


## Exercise 17: Concatenate Author Name

Given `first = "Octavia"` and `last = "Butler"`, create `author_full = "Octavia Butler"` and print it.

In [27]:
first = "Octavia"
last = "Butler"
author_full = first + " " + last
print(author_full)

Octavia Butler


## Exercise 18: Edition Equality (Boolean Only)

Let `edition_text = "2"` and `edition_num = 2`. Compute `same = int(edition_text) == edition_num` and print `same`.

In [28]:
edition_text = "2"
edition_num = 2
same = int(edition_text) == edition_num
print(same)

True


## Exercise 19: Copy Count Update (Arithmetic)

Start with `copies = 3`. Add a returned copy (`+1`) and subtract a lost copy (`-1`). Print the final count (you may change the increments).

In [29]:
copies = 3
copies = copies + 1   # returned
copies = copies - 1   # lost
print(copies)

3


## Exercise 20: Modern Publication (Boolean Only)

Ask for a publication year and compute a boolean `modern = (year >= 2000)`. Print `modern`.

In [59]:
year = int(input("Publication year: "))
modern = (year >= 2000)
print(modern)

Publication year: 2000
True


## Exercise 21: Hold Ready (Boolean Only)

Given `hold_ready = True`, print the boolean and a simple message on a single line without branching, e.g., `True — status recorded`.

In [31]:
hold_ready = True
print(f"{hold_ready} — status recorded")

True — status recorded


## Exercise 22: Replace Substring in Title

Let `title = "The Color of Magic"`. Replace `"Color"` with `"Colour"` and print the result.

In [32]:
title = "The Color of Magic"
updated = title.replace("Color", "Colour")
print(updated)

The Colour of Magic


## Exercise 23: Keyword Present (Boolean Only)

Given `title = "The Left Hand of Darkness"` and `keyword = "Hand"`, compute `present = title.find(keyword) != -1` and print `present`.

In [33]:
title = "The Left Hand of Darkness"
keyword = "Hand"
present = title.find(keyword) != -1
print(present)

True


## Exercise 24: Extract Cutter by Position (No Lists)

With `call_no = "QA.76.P98"`, find the last `'.'` index and slice the cutter part. Print only the cutter.

In [34]:
call_no = "QA.76.P98"
last_dot = call_no.rfind(".")
cutter = call_no[last_dot+1:]
print(cutter)

P98


## Exercise 25: Rating Validity (Boolean Only)

Ask for a rating `0–5`. Compute `valid = (rating >= 0) and (rating <= 5)` and print `valid`.

In [60]:
rating = float(input("Rating 0–5: "))
valid = (rating >= 0) and (rating <= 5)
print(valid)

Rating 0–5: 3
True


## Exercise 26: Tiny Catalog Line

Create `title`, `author`, and `year`. Print `"Title — Author (Year)"` exactly in that format using an f-string.

In [61]:
title = "Then She Was Gone"
author = "Lisa Jewell"
year = 2018
print(f"{title} — {author} ({year})")

Then She Was Gone — Lisa Jewell (2018)


## Exercise 27: Average Rating (Rounded)

Given `avg_rating = 4.2667`, print it rounded to two decimals using an f-string format specifier.

In [37]:
avg_rating = 4.2667
print(f"{avg_rating:.2f}")

4.27


## Exercise 28: Query Normalization

Ask for a search term via `input()` and normalize it by stripping spaces and lowercasing. Print the normalized query.

In [62]:
query = input("Search term: ")
normalized = query.strip().lower()
print(normalized)

Search term: Frank
frank


## Exercise 29: Borrower Card Line

Given `name = "Avery"` and `id_num = 1024`, print: `"Borrower: Avery (ID: 1024)"`.

In [39]:
name = "Avery"
id_num = 1024
print(f"Borrower: {name} (ID: {id_num})")

Borrower: Avery (ID: 1024)


## Exercise 30: Stock State (No Branching)

Let `copies = 1`. Compute booleans: `none = (copies == 0)`, `single = (copies == 1)`, `many = (copies > 1)`. Print all three in one line.

In [40]:
copies = 1
none_ = (copies == 0)
single = (copies == 1)
many = (copies > 1)
print(none_, single, many)

False True False
